title: Proyecto VOD
description: Una aplicación de video bajo demanda estilo Netflix
url: https://franciscoleivan.github.io/proyecto-vod/
baseurl: /proyecto-vod
repository: FranciscoLeivaN/proyecto-vod
